version: "3.8"

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15
    container_name: ideaboard-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ideaboard
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ideaboard-network

  # Backend API (for development)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: ideaboard-backend
    environment:
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/ideaboard?schema=public
      - PORT=5000
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - ideaboard-network
    profiles:
      - full-stack

  # Frontend (for development)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: ideaboard-frontend
    environment:
      - VITE_API_URL=http://localhost:5000
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - ideaboard-network
    profiles:
      - full-stack

volumes:
  postgres_data:

networks:
  ideaboard-network:
    driver: bridge
